import { mkdir, writeFile } from "node:fs/promises";
import { projects, publications, education, experience, skillGroups } from "../assets/content.js";

const text = {
  en: {
    lang: "en", prefix: "", switchLabel: "中文", nav: ["Research", "Projects", "Publications", "About"],
    homeEyebrow: "Mechanical engineering × scientific machine learning", homeTitle: "Researching how learning systems can reshape engineering design.", homeIntro: "A growing collection of research directions, project notes, methods, and publications across generative design, surrogate modeling, and engineering intelligence.", enter: "Enter research", browse: "Browse projects →", caption: "Researcher in engineering design and scientific machine learning", explore: "Explore the work by section.", now: "Current questions", nowText: "How can engineering models become faster, differentiable, controllable, and useful inside real design workflows?", contact: "Start a conversation ↗",
    portal: [["Research", "Themes, questions, and approaches"], ["Projects", "Expandable records of systems and experiments"], ["Publications", "Peer-reviewed research output"], ["About", "Background, experience, and contact"]],
    researchTitle: "Research directions", researchIntro: "The site is organized around evolving research questions—not a résumé timeline. Each direction can grow into its own collection of notes, experiments, and projects.", themes: [["Generative engineering", "Controllable inverse design for mechanical structures, metamaterials, and graph-based systems.", "Generative models · Inverse design · Design control"], ["Surrogate modeling", "Fast graph- and grid-based predictors for nonlinear fields, deformation, and optimization.", "GNN · U-Net · Differentiable optimization"], ["Engineering intelligence", "Scientific machine learning, knowledge transfer, and language models embedded in engineering workflows.", "Scientific ML · Knowledge systems · LLM"]],
    projectsTitle: "Project archive", projectsIntro: "Projects are maintained as expandable research records. Open one to see its question, contribution, and methods; future work can be added without lengthening the homepage.", open: "Open project", question: "Research question", contribution: "Contribution", methods: "Methods",
    publicationsTitle: "Publications", publicationsIntro: "Peer-reviewed work and selected research output, grouped as a separate reference collection.", aboutTitle: "About", aboutIntro: "Chonghui Zhang is a mechanical engineering researcher working across computational design, scientific machine learning, and AI-assisted engineering workflows.", education: "Education", experience: "Experience", capabilities: "Methods & tools", contactTitle: "Discuss a research question or collaboration.", footer: "A living research archive."
  },
  zh: {
    lang: "zh-CN", prefix: "/zh", switchLabel: "English", nav: ["研究", "项目", "论文", "关于"],
    homeEyebrow: "机械工程 × 科学机器学习", homeTitle: "研究学习系统如何重塑工程设计。", homeIntro: "持续整理生成式设计、代理建模与工程智能领域的研究方向、项目记录、方法和论文。", enter: "进入研究", browse: "浏览项目 →", caption: "工程设计与科学机器学习研究者", explore: "按主题进入研究内容。", now: "当前关注的问题", nowText: "如何让工程模型更快速、可微、可控，并真正进入实际设计流程？", contact: "与我讨论 ↗",
    portal: [["研究", "研究主题、问题与方法"], ["项目", "可展开的系统与实验记录"], ["论文", "同行评议研究成果"], ["关于", "研究背景、经历与联系"]],
    researchTitle: "研究方向", researchIntro: "网站围绕持续演化的研究问题组织，而不是简历时间线。每个方向都可以逐步扩展为独立的笔记、实验与项目集合。", themes: [["工程生成式设计", "面向机械结构、超材料与图系统的可控逆向设计。", "生成模型 · 逆向设计 · 设计控制"], ["代理建模", "面向非线性场、形变与优化的快速图和网格预测模型。", "图神经网络 · U-Net · 可微优化"], ["工程智能", "嵌入工程工作流的科学机器学习、知识迁移与语言模型。", "科学机器学习 · 知识系统 · 大语言模型"]],
    projectsTitle: "项目档案", projectsIntro: "项目以可展开的研究记录维护。展开后可以查看研究问题、贡献与方法，未来新增内容也不会让主页无限变长。", open: "展开项目", question: "研究问题", contribution: "主要贡献", methods: "方法",
    publicationsTitle: "论文", publicationsIntro: "将同行评议论文与代表性研究成果作为独立的参考集合。", aboutTitle: "关于", aboutIntro: "Chonghui Zhang 是机械工程研究者，研究计算设计、科学机器学习与 AI 辅助工程工作流。", education: "教育背景", experience: "研究经历", capabilities: "方法与工具", contactTitle: "讨论研究问题或合作。", footer: "持续生长的研究档案。"
  }
};

const routes = ["research", "projects", "publications", "about"];
const esc = value => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const loc = (value, language) => value[language];
const route = (c, name = "") => `${c.prefix}/${name}${name ? "/" : ""}`;
const languageRoute = (language, page) => language === "en" ? `/zh/${page === "home" ? "" : `${page}/`}` : `/${page === "home" ? "" : `${page}/`}`;

function layout(language, page, title, description, body) {
  const c = text[language];
  const nav = routes.map((name, i) => `<a href="${route(c,name)}"${page === name ? ' aria-current="page"' : ""}>${c.nav[i]}</a>`).join("");
  return `<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#070b12"><title>${esc(title)} — Chonghui Zhang</title><link rel="stylesheet" href="/assets/styles.css"></head><body data-page="${page}"><a class="skip-link" href="#main">${language === "en" ? "Skip to content" : "跳转到主要内容"}</a><header class="site-header"><a class="brand" href="${route(c)}"><strong>Chonghui Zhang</strong><span>${language === "en" ? "Research notes" : "研究笔记"}</span></a><nav aria-label="Primary navigation">${nav}</nav><a class="language-link" href="${languageRoute(language,page)}" lang="${language === "en" ? "zh-CN" : "en"}">${c.switchLabel}</a></header><main id="main">${body}</main><footer class="site-footer shell"><span>© ${new Date().getFullYear()} Chonghui Zhang</span><span>${c.footer}</span><a href="mailto:chonghui.zhang@mail.mcgill.ca">Email ↗</a></footer></body></html>`;
}

function home(language) {
  const c = text[language];
  const cards = c.portal.map(([title,note],i) => `<a href="${route(c,routes[i])}"><span>0${i+1}</span><h3>${title}</h3><p>${note}</p><b>↗</b></a>`).join("");
  const body = `<section class="home-hero shell"><div><p class="eyebrow">${c.homeEyebrow}</p><h1>Chonghui Zhang</h1><h2>${c.homeTitle}</h2><p class="lede">${c.homeIntro}</p><div class="actions"><a class="button primary" href="${route(c,"research")}"><span>${c.enter}</span><span>↗</span></a><a class="text-link" href="${route(c,"projects")}">${c.browse}</a></div></div><aside class="portrait-card"><img src="/assets/chonghui-zhang-dark.png" alt="Chonghui Zhang"><div><span>ME × SCI ML</span><strong>${c.caption}</strong></div></aside></section><section class="portal shell"><div class="section-intro"><p class="kicker">01 / INDEX</p><h2>${c.explore}</h2></div><div class="portal-grid">${cards}</div></section><section class="home-note shell"><p class="kicker">02 / NOW</p><div><h2>${c.now}</h2><p>${c.nowText}</p></div><a class="text-link" href="mailto:chonghui.zhang@mail.mcgill.ca">${c.contact}</a></section>`;
  return layout(language,"home",language === "en" ? "Research" : "研究",c.homeIntro,body);
}

function research(language) { const c=text[language]; const list=c.themes.map(([title,note,methods],i)=>`<article><span>0${i+1}</span><div><h2>${title}</h2><p>${note}</p></div><small>${methods}</small></article>`).join(""); return layout(language,"research",c.nav[0],c.researchIntro,`<div class="page-shell shell"><header class="page-heading"><p class="kicker">01 / RESEARCH</p><h1>${c.researchTitle}</h1><p>${c.researchIntro}</p></header><div class="theme-list">${list}</div></div>`); }
function projectPage(language) { const c=text[language]; const list=projects.map((p,i)=>`<details id="${esc(p.slug)}"><summary><span>${String(i+1).padStart(2,"0")}</span><div><small>${esc(p.code)} · ${esc(p.period)}</small><h2>${esc(loc(p.title,language))}</h2></div><b><i>${c.open}</i> +</b></summary><div class="project-body"><div><span>${c.question}</span><p>${esc(loc(p.summary,language))}</p></div><div><span>${c.contribution}</span><p>${esc(loc(p.contribution,language))}</p></div><div><span>${c.methods}</span><p>${p.methods.map(esc).join(" · ")}</p></div></div></details>`).join(""); return layout(language,"projects",c.nav[1],c.projectsIntro,`<div class="page-shell shell"><header class="page-heading"><p class="kicker">02 / PROJECTS</p><h1>${c.projectsTitle}</h1><p>${c.projectsIntro}</p></header><div class="project-index">${list}</div></div>`); }
function publicationPage(language) { const c=text[language]; const list=publications.map((p,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><div><h2>${esc(p.title)}</h2><p>${esc(p.authors)}</p></div><aside><strong>${esc(p.year)}</strong><small>${esc(p.venue)}</small></aside></article>`).join(""); return layout(language,"publications",c.nav[2],c.publicationsIntro,`<div class="page-shell shell"><header class="page-heading"><p class="kicker">03 / PUBLICATIONS</p><h1>${c.publicationsTitle}</h1><p>${c.publicationsIntro}</p></header><div class="publication-index">${list}</div></div>`); }
function about(language) { const c=text[language]; const timeline=(items,org,detail)=>items.map(x=>`<article class="timeline"><span>${esc(x.period)}</span><div><h3>${esc(loc(x[org],language))}</h3><p>${esc(loc(x[detail],language))}</p><small>${esc(loc(x.note,language))}</small></div></article>`).join(""); const skills=skillGroups.map(g=>`<div><span>${esc(loc(g.label,language))}</span><p>${g.items.map(esc).join(" · ")}</p></div>`).join(""); return layout(language,"about",c.nav[3],c.aboutIntro,`<div class="page-shell shell"><header class="page-heading"><p class="kicker">04 / ABOUT</p><h1>${c.aboutTitle}</h1><p>${c.aboutIntro}</p></header><div class="about-grid"><section><h2>${c.education}</h2>${timeline(education,"institution","degree")}</section><section><h2>${c.experience}</h2>${timeline(experience,"organization","role")}</section><aside class="capability-panel"><h2>${c.capabilities}</h2>${skills}</aside></div><section class="contact-block"><p class="kicker">EMAIL</p><h2>${c.contactTitle}</h2><a href="mailto:chonghui.zhang@mail.mcgill.ca">chonghui.zhang@mail.mcgill.ca ↗</a></section></div>`); }

const renderers={home,research,projects:projectPage,publications:publicationPage,about};
for (const language of ["en","zh"]) for (const page of ["home",...routes]) { const directory=language === "en" ? (page === "home" ? "." : page) : (page === "home" ? "zh" : `zh/${page}`); await mkdir(new URL(`../${directory}/`,import.meta.url),{recursive:true}); await writeFile(new URL(`../${directory}/index.html`,import.meta.url),renderers[page](language),"utf8"); }
console.log("Generated 10 static HTML pages.");
